name: Push to Replicate

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Enter the model name, like "alice/bunny-detector"'
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Replicate API token
        run: echo "${{ secrets.REPLICATE_API_TOKEN }}" | cog login

      - name: Push Model to Replicate
        run: cog push r8.im/${{ inputs.model_name }}
